"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = "$time"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[aws]
disabled = true

[line_break]
disabled = true
